baseURL = 'https://escalembur.github.io/'
languageCode = 'pt-br'
title = 'Escalembur'
theme = 'hugo.386'
DefaultContentLanguage = "pt-br" # Change this to change the site's language
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Estúdio Calembur"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Um coletivo brasileiro de desenvolvimento de jogos!" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Calembur é um jogo de palavras que, embora semelhantes no som, têm significados diversos, ocasionando equívocos."

    # The name to display in the copyright section in the footer
    copyrightname = ". ... -.-. .- .-.. . -- -... ..- .-."

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Urls for social networks
    # facebook = "https://calembur.itch.io/"
    # twitter = "https://twitter.com"
    # linkedin = "https://linkedin.com"
    # github = "https://github.com"
    # gitlab = "https://gitlab.com"
    itch = "https://calembur.itch.io/"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 10.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Estúdio Calembur"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    	# Text to go before copyright information
	#prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    	# Text to go between copyright and hugo disclaimer (if enabled)
    	# suffix = "Example site"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "sobre" # An unique identifier for the button
    name = "Sobre"       # A display name for the button
    url = "/sobre/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  # [[menu.main]]
  #   identifier = "posts"
  #   name = "All posts"
  #   url = "/post/"       # The path can lead to a content folder too.
  #   weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
